### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ands** [Thekla/thekla_atlas#2]
Hi, I might want to use and modify this code for my master's thesis. I found licensing information for the external (and nv) libs but what about the thekla_atlas code itself? The LICENSE file is empty. Am I allowed to use and modify that code?
Thanks : )

(Just finished playing The Witness. Definitely one of the best games I've played so far - Thank you!)

**Comment by castano** [comment]
Thanks for pointing this out! License should be the MIT license or something liberal along those lines. I'll update the license asap. I'd also recommend taking a look at Microsoft's uvatlas tool: https://uvatlas.codeplex.com/

**Comment by ands** [comment]
Thanks! Yeah, I've seen the uvatlas tool and might try both : )
