### ISSUE TITLE
NVIDIA copyright?

### ISSUE THREAD

**Issue by patwretchedsuspect** [Thekla/thekla_atlas#24]
Some files (in src/nv* folders) have
> Copyright NVIDIA Corporation 2006 -- Ignacio Castano <icastano@nvidia.com>
> Copyright NVIDIA Corporation 2007 -- Denis Kovacs <den.kovacs@gmail.com>
> Copyright NVIDIA Corporation 2008 -- Ignacio Castano <icastano@nvidia.com>

and the similar. The files do not appear to have a separate license in them, nor instructions to reproduce those copyright notices in any other form.

Are those an external dependence from
https://github.com/castano/nvidia-texture-tools
https://github.com/castano/nvidia-mesh-tools
? Should I comply with the respective licenses of those projects in addition to the thekla_atlas' license or are those files re-licensed under the current thekla_atlas' license _with the permission of NVIDIA_?

The main problem is that while all of them appear to fall under the MIT license, but thekla_atlas asks only to include
> Copyright (c) 2013 Thekla, Inc

, while nvidia-texture-tools asks to include:
> Copyright (c) 2009-2017 Ignacio Castaño
> Copyright (c) 2007-2009 NVIDIA Corporation

and the license file for the nvidia-mesh-tools is missing (the old location on code.google.com suggests MIT license, but doesn't specify the copyright notice in a separate file).

There was a brief mention of it in #2: "licensing information for... nv libs...", but the topicstarter didn't elaborate on that.

**Comment by castano** [comment]
Both of the nvidia libraries are licensed under the MIT License that you can find here:

https://github.com/castano/nvidia-texture-tools/blob/master/LICENSE

Looks like the LICENSE file for the mesh tools was missing, the google code site used to specify that and provide a link to it, but that was lost on the migration. I've added it to the github project.

thekla_atlas is under the same MIT license. I've also added an ATTRIBUTION file that lists the projects that it depends on and their respective licenses.
