### ISSUE TITLE
Missing 2-clause-BSD license for tinyobj?

### ISSUE THREAD

**Issue by patwretchedsuspect** [Thekla/thekla_atlas#25]
extern/tinyobj/tiny_obj_loader.h reads:
> // Copyright 2012-2015, Syoyo Fujita.
> //
> // Licensed under 2-clause BSD liecense.

(the last word is written with an error in the original) but the text of the license itself is missing. The [2-clause BSD license](https://opensource.org/licenses/BSD-2-Clause) demands retaining the list of conditions of the license and the disclaimer at the end of the license.

To be fair, it doesn't appear that the text of the license was present in the code at the time of its inclusion in the project, so I'm not sure how "retain" plays out here (while the demand to "reproduce" the list of conditions and etc. is reserved for the "redistributions in binary").

It seems like the current version of the tinyobjloader switched to MIT license:
https://github.com/syoyo/tinyobjloader

**Comment by castano** [comment]
Thanks for pointing that out. I've added the full license text to the ATTRIBUTION file. Note that tinyobj is only necessary for the example code. If you only use the thekla_atlas library, you don't need to provide attribution.
