### ISSUE TITLE
ATTRIBUTION is missing a license

### ISSUE THREAD

**Issue by patwretchedsuspect** [Thekla/thekla_atlas#26]
The file src/nvcore/scanf.c has:
> Copyright (c) 1990, 1993
> The Regents of the University of California.  All rights reserved.

with a note "this code is derived from..." and a separate license.
The license _appears_ to be the 3-clause/New-BSD, or 4-clause/BSD-old with removed advertising clause (judging by the missing item 3).

**Comment by castano** [comment]
I've removed this dependency instead. That code was only necessary for old visual studio versions that didn't provide the vsscanf function. That function is not even used on this project, so removing it should be fairly safe.
