### ISSUE TITLE
bug fix? 

### ISSUE THREAD

**Issue by Simoncl** [Thekla/thekla_atlas#32]
Orignal.
mesh->vertex_array[nv+v].uv[0] = shapes[s].mesh.texcoords[v * 3 + 0];      
mesh->vertex_array[nv+v].uv[1] = shapes[s].mesh.texcoords[v * 3 + 1];

Shouldn't this be.
 mesh->vertex_array[nv+v].uv[0] = shapes[s].mesh.texcoords[v * 2 + 0];      
mesh->vertex_array[nv+v].uv[1] = shapes[s].mesh.texcoords[v * 2 + 1];

I was getting a crash before I changed it.

**Comment by castano** [comment]
Thanks for the bug report!
