### ISSUE TITLE
Doesn't generate an output mesh?

### ISSUE THREAD

**Issue by DelvarWorld** [Thekla/thekla_atlas#4]
Forgive me if I'm entirely misunderstanding this project, but it doesn't seem like an output mesh (with the updated UVs) are exported? Or is the output of this project simply the image?

**Comment by castano** [comment]
The result is in the Atlas_Output_Mesh structure. The test app does not write the contents to disk, that code is just intended to be an example on how to use the API, it's not a tool that is ready to use. If you'd like to improve it, I'd be happy to review and integrate your changes.
