### ISSUE TITLE
Missing files: can't compile

### ISSUE THREAD

**Issue by Shell64** [Thekla/thekla_atlas#5]
ImageIO is missing from nvimage folder (but I got it from nvidia texture tools which is the same I guess).

There are more and I don't know where they come from and they are not in thekla atlas:

#include "reducer/ReducerBuilder.h"
#include "reducer/ReducerMesh.h"
#include "reducer/ReducerVertex.h"
#include "reducer/ReducerFace.h"

**Comment by castano** [comment]
Sorry, these errors should be fixed now.
