### ISSUE TITLE
Reliably fails for Spheres, Ellipsoids, and Toroids that are transformed in any way

### ISSUE THREAD

**Issue by JSandusky** [Thekla/thekla_atlas#8]
Atlas::computeCharts begins a descent into a non-recoverable crash state with reliable reproducibility (though it requires a GUI to perform the transforms that fail, fine iteration over a sphere surface should work though).

The first sign of impending failure is the assertion in AtlasBuilder::evaluatestraightnessMetric @ line: 947  failing (nvDebugCheck(l_in != 0.0f)). Relocating seeds will then fail, AtlasBuilder::addFaceToChart will fail, and AtlasBuilder::mergeCharts will crash. Everything after the first assertion is basicaly just debugger default initializated values.

Said primitives function fine when combined with others, if they become isolated in any fashion they will reliabily fail unless at an identity transform. 

Changing nvMath's epsilon definition to a finer value results in an entirely different set of errors, so the problem is probably in nvMath and not the Thekla portions itself .... assuming that value changes are resulting in failing fast.

**Comment by JSandusky** [comment]
Error in my data. My voxelizer would occasionally emit nearly degenerate quads if the dual verts nearly coalesced, with spherical shapes being the most likely to do such during root finding.

**Comment by castano** [comment]
No worries! Glad thekla_atlas is working for you.

**Comment by JSandusky** [comment]
Had it working in 30 minutes over C++/CLI. It's been dreamy, thanks for sharing it!
